JWT_ALGO = "HS256"

HASH_ALGO = "sha256"
HASH_ITERS = 100_000
SALT_BYTE_LEN = 8
SALT_HEX_LEN = SALT_BYTE_LEN * 2
HASHED_PASSWORD_LEN = 64

FIELD_NAME_MAX_LEN = 50
FIELD_DESC_MAX_LEN = 10_000

FIELD_EMAIL_MAX_LEN = 254

PATTERN_PWD = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{6,}$"
