SECRET_KEY = "key"
JWT_ALGO = "HS256"
JWT_TIMEOUT_SECONDS = 60 * 60

HASH_ALGO = "sha256"
HASH_ITERS = 100_000
SALT_BYTE_LENGTH = 8
SALT_HEX_LENGTH = 16

PATTERN_PWD = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{6,}$"
PATTERN_HTTP_BEARER_AUTH = "^Bearer ([A-Za-z0-9_-]+\\.){2}[A-Za-z0-9_-]*$"

PAGINATE_MAX_ITEMS = 3
